global_config:
  seed: 5959
  device: "cuda"
  is_mp: True
---
data_config:
  data_path: "./data/"
  dataset_name: "CIFAR10"
  num_shards: 200
  iid: False
---
fed_config:
  C: 0.1
  K: 100
  R: 500
  E: 5
  B: 10
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.01
  momentum: 0.9
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: [0,]
---
model_config:
  name: CNN2
  in_channels: 3
  hidden_channels: 32
  num_hiddens: 512
  num_classes: 10
---
log_config:
  log_path: "log/17"
  log_name:  "FL.log"
  tb_port: 5253
  tb_host: "0.0.0.0"
